DROP TABLE IF EXISTS public.client;

CREATE TABLE IF NOT EXISTS public.client
(
    client_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    address character varying COLLATE pg_catalog."default" NULL,
    CONSTRAINT client_pk PRIMARY KEY (client_id)
)

-- TODO why is this here? What does it do? For some reason if I comment it out the tables don't get created.
TABLESPACE pg_default;

DROP TABLE IF EXISTS public.order;

-- TODO date_submitted needs to be a date type will have to research and do research on UTC and server time.
CREATE TABLE IF NOT EXISTS public.order
(
    order_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    client_id integer NOT NULL,
    date_submited character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT order_pk PRIMARY KEY (order_id)
)

TABLESPACE pg_default;

DROP TABLE IF EXISTS public.order_product;

CREATE TABLE IF NOT EXISTS public.order_product
(
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    amount integer NOT NULL
)

TABLESPACE pg_default;

DROP TABLE IF EXISTS public.product;

CREATE TABLE IF NOT EXISTS public.product
(
    product_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT product_pk PRIMARY KEY (product_id)
)

TABLESPACE pg_default;

DROP TABLE IF EXISTS public.user;

CREATE TABLE IF NOT EXISTS public.user
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    login_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_pk PRIMARY KEY (user_id)
)

TABLESPACE pg_default;

-- TODO do dependancies / joins after all tables created