# See E:\Working\wetesa-0\docs\Decision Records\Architecture\ADR-012 Linters
# based on [maratori Golden Config](https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322)
# [All settings](https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml)

version: "2"

issues:
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 50

formatters:
  enable:
    - gci # reorders imports
    - goimports # adds missing imports and removes unreferenced imports, also formats code to gofmt rules
    - golines # checks if code is formatted, and fixes long lines, tries to use goimports first then gofmt

  ## disabled
    #- gofmt # default go formatter. only needed it goimports is not used
    #- gofumpt # [replaced by goimports] checks if code and import statements are formatted, with additional rules

  settings:
    gci:
      # Section configuration to compare against.
      # Section names are case-insensitive and may contain parameters in ().
      # The default order of sections is `standard > default > custom > blank > dot > alias > localmodule`,
      # If `custom-order` is `true`, it follows the order of `sections` option.
      # Default: ["standard", "default"]
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/org/project) # Custom section: groups all imports with the specified Prefix.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
        - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.

    goimports:
      # A list of prefixes, which, if set, checks import paths
      # with the given prefixes are grouped after 3rd-party packages.
      # Default: []
      local-prefixes:
        - github.com/my/project

    golines:
      # Target maximum line length.
      # Default: 100
      max-len: 120
      
  exclusions:
    paths:
      # This file has long lines on purpose. It is easier to read that way.
      # Unfortunately no way to turn off just golines. Have to turn off all formatters. VS code should handle most of it.
      - internal/server/routes.go

linters:
  enable:  




